name: first

on: [push]

jobs:
    job1: 
        name: First job
        runs-on: ubantu-latest
        steps:
            -name: Step One
             uses: actions/checkout@v4
            -name: Step Two
             run: env | sort
    job2: 
        name: Seconde job
        runs-on: windows-latest
        steps:
            -name: Step One 
             uses: actions/checkout@v4
            -name: Step Two
             run: "Get-ChildItem Env: | Sort-Object Name"
    
    
    
